// The video's sound effects, generated by ElevenLabs and loudness-matched so the scenes can
// mix them with simple relative volumes. Cached: rerunning only pays for new or changed ones.
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { ensureCredits, soundEffect } from './elevenlabs.mjs';
import { normalize } from './audio.mjs';
import { OUT, PUBLIC } from './paths.mjs';

/** id → prompt and length (s). Ids are referenced from src/sfx.ts. */
export const EFFECTS = {
  'swim-whoosh': ['Quick playful underwater whoosh as a small cartoon stingray zips past, bubbly swish', 1.2],
  bubbles: ['Short burst of cute cartoon underwater bubbles popping, light and bright', 1.5],
  boing: ['Cartoon boing, a bouncy spring sound, cute and comedic', 0.8],
  dizzy: ['Cartoon dizzy spin: wobbly slide whistle with little tweeting birds, comedic', 2],
  thud: ['Comedic cartoon thump of a window dropping onto a pile, soft wooden bonk', 0.6],
  sweep: ['Fast magical whoosh that sweeps everything into one place, rising swoosh ending in a soft pop', 1.5],
  typing: ['Fast soft laptop keyboard typing, clean and close, no background noise', 3],
  click: ['Single soft computer mouse click, clean and crisp', 0.5],
  chime: ['Bright happy success chime, sparkly two-note ding for an app', 1.2],
  confetti: ['Party popper pop followed by a sparkly confetti shower, joyful', 1.8],
  rewind: ['Short playful cartoon tape-rewind zip', 1],
  stamp: ['Rubber stamp thump with a cheerful little sparkle, approval', 0.8],
  pop: ['Soft satisfying cartoon pop as a tile appears, light and clean', 0.5],
  shimmer: ['Magical shimmering sparkle reveal for a logo, gentle and bright', 2],
};

/** Approximate credits per generation. */
const COST = 200;

async function main() {
  const rawDir = path.join(OUT, 'sfx-raw');
  const dir = path.join(PUBLIC, 'audio', 'sfx');
  await mkdir(rawDir, { recursive: true });
  await mkdir(dir, { recursive: true });
  await ensureCredits(Object.keys(EFFECTS).length * COST, 'the sound effects');

  for (const [id, [text, durationSeconds]] of Object.entries(EFFECTS)) {
    const { audio, fresh } = await soundEffect({ text, durationSeconds });
    const raw = path.join(rawDir, `${id}.mp3`);
    await writeFile(raw, audio);
    await normalize(raw, path.join(dir, `${id}.mp3`), { i: -18, tp: -2, bitrate: '160k', channels: 2 });
    console.log(`${id.padEnd(12)} ${fresh ? 'new' : 'cached'}`);
  }
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
