//! Prompt builders for the Advisor's Copilot sessions: the catalog-driven deep
//! review, the targeted Verify re-check, and the inline "Explain" answer.

use std::collections::HashSet;
use std::fmt::Write as _;

use super::catalog::{category_title, RuleDef, CATALOG};
use super::tools::{COMPLETE_TOOL, FINDING_TOOL, PROGRESS_TOOL, VERDICT_TOOL};
use crate::types::{AdvisorFinding, AdvisorRunRequest};

/// What a Rayfin app is and where its parts live, for the reviewer's bearings.
const APP_SHAPE: &str = "a Microsoft Fabric app: a TypeScript/React frontend plus a Rayfin backend configured in `rayfin/rayfin.yml`. \
Single-package apps keep the frontend in `src/` and the data model and functions under `rayfin/`. Workspace apps, such as \
those from the Rayfin CLI's Universal App, keep each in the npm package `rayfin.yml` names with `services.<service>.path`, \
such as `packages/frontend`, `packages/data` and `packages/functions`";

const GROUND_RULES: &str = "\
- READ-ONLY: never create, edit, or delete files, and never run shell commands, installs, builds, deploys, or `rayfin up`. Those tools are disabled in this session.
- Don't open `.env*` files, keys, or other secret stores: secret checks already ran locally, and those reads are blocked.
- Report only real issues you verified by reading this app's code. No speculative or generic advice — when a rule doesn't apply or the app already follows it, record that with the progress tool instead of inventing a finding.
- Recommend only APIs, decorators, and options documented for the installed Rayfin version (for example, Rayfin fields have no `index` option). When unsure, check the sources below first.
- Never copy secret values into a report; mask them (for example `sk-…`).";

const SOURCES: &str = "\
1. `.agents/skills/rayfin/SKILL.md` — generated by the installed Rayfin CLI (if present).
2. `node_modules/@microsoft/rayfin-guide/assets/docs/**/*.md` — the version-locked Rayfin guide; grep it for the topic you're checking.
3. `node_modules/@microsoft/rayfin-*/dist/**/*.d.ts` — exact API signatures.
4. https://rayfin.ai — the live docs (append `.md` to any docs URL; the index is https://rayfin.ai/llms.txt). Use web_fetch.";

fn bullet_list(items: impl IntoIterator<Item = String>) -> String {
  let lines: Vec<String> = items.into_iter().map(|s| format!("- {s}")).collect();
  if lines.is_empty() {
    "- (none)".to_string()
  } else {
    lines.join("\n")
  }
}

/// Most earlier deep-review findings a new review is asked to re-check.
const MAX_PREVIOUS: usize = 30;

/// ` — file:line` for a finding reference, when it has a location.
fn location_suffix(file: &Option<String>, line: Option<u32>) -> String {
  match (file, line) {
    (Some(f), Some(l)) => format!(" — {f}:{l}"),
    (Some(f), None) => format!(" — {f}"),
    _ => String::new(),
  }
}

/// The deep-review instruction: ground rules, project facts, sources, the quick
/// findings not to repeat, the applicable AI rules by category, and how to report.
pub fn review_prompt(req: &AdvisorRunRequest, rules: &[&RuleDef]) -> String {
  let facts = &req.facts;
  let mut out = String::new();
  let _ = writeln!(
    out,
    "You are the Advisor for a Rayfin app ({APP_SHAPE}). Perform a careful, READ-ONLY review of the app in this directory against the rules below.\n"
  );
  let _ = writeln!(out, "## Ground rules\n{GROUND_RULES}\n");

  let _ = writeln!(out, "## Project facts");
  if let Some(stack) = facts.stack.as_deref().filter(|s| !s.is_empty()) {
    let _ = writeln!(out, "- Stack: {stack}");
  }
  let services = if facts.services.is_empty() { "(none)".to_string() } else { facts.services.join(", ") };
  let _ = writeln!(out, "- Enabled rayfin.yml services: {services}");
  let versions: Vec<String> = facts
    .versions
    .iter()
    .map(|v| {
      let installed = v.installed.as_deref().unwrap_or("not installed");
      match v.latest.as_deref() {
        Some(latest) => format!("{} {installed} (latest {latest})", v.name),
        None => format!("{} {installed}", v.name),
      }
    })
    .collect();
  if !versions.is_empty() {
    let _ = writeln!(out, "- Rayfin packages: {}", versions.join("; "));
  }
  let entities: Vec<String> = facts
    .entities
    .iter()
    .map(|e| format!("{} ({}) — {}", e.name, e.file, e.access))
    .collect();
  let _ = writeln!(
    out,
    "- Entities: {}",
    if entities.is_empty() { "(none)".to_string() } else { entities.join("; ") }
  );
  let _ = writeln!(
    out,
    "- These rules were written against Rayfin {}. If the installed version differs, confirm behavior in the version-matched sources.\n",
    CATALOG.rayfin_baseline
  );

  let _ = writeln!(out, "## Version-matched sources (read what you need, in this order)\n{SOURCES}\n");

  let quick = bullet_list(
    req
      .quick
      .iter()
      .map(|q| format!("[{}] {}{}", q.rule_id, q.title, location_suffix(&q.file, q.line))),
  );
  let _ = writeln!(
    out,
    "## Already reported by Fabricator's quick checks — do NOT report these again\n{quick}\n"
  );

  let listed: HashSet<&str> = rules.iter().map(|r| r.id.as_str()).collect();
  let previous: Vec<String> = req
    .previous
    .iter()
    .filter(|p| listed.contains(p.rule_id.as_str()))
    .take(MAX_PREVIOUS)
    .map(|p| format!("[{}] {}{}", p.rule_id, p.title, location_suffix(&p.file, p.line)))
    .collect();
  if !previous.is_empty() {
    let _ = writeln!(
      out,
      "## Reported by the last deep review — re-check each one\nRe-read the code for each of these. If the issue is still there, report it again with `{FINDING_TOOL}` (same rule, current evidence); if it's fixed, don't report it. Count them when you record each rule's status.\n{}\n",
      bullet_list(previous)
    );
  }

  let _ = writeln!(out, "## Rules to evaluate");
  let mut current = "";
  for rule in rules {
    if rule.category != current {
      current = &rule.category;
      let _ = writeln!(out, "\n### {}", category_title(current));
    }
    let check = rule.check.as_deref().unwrap_or(&rule.summary);
    let _ = writeln!(
      out,
      "- `{}` (default severity: {}) — {}. Check: {} Documented fix: {}",
      rule.id, rule.severity, rule.title, check, rule.fix
    );
  }

  let _ = writeln!(
    out,
    "\n## How to report
- For each verified issue, call `{FINDING_TOOL}` right away (don't save them for the end) with a ruleId from the list, the project-relative `file`, `startLine`/`endLine`, and an `excerpt` copied EXACTLY from the file (1–12 lines). Report each rule at most once: put the clearest place in `file` and every other place in `otherLocations`. Keep the title short, the detail specific to this app (1–3 sentences), and the recommendation concrete.
- Severity: start from the rule's default. Use high only for unauthenticated or public access to data, one user reaching another user's data, exposed secrets, or silent data loss; lower it when the impact is limited.
- After finishing each category, call `{PROGRESS_TOOL}` with a status for EVERY rule in that category: `fail` (you reported a finding), `pass` (the app follows it), `na` (it doesn't apply), or `skipped` (you couldn't check it — add a short note).
- When you're done, call `{COMPLETE_TOOL}` with a plain-language summary of the app's overall state in one or two short sentences (under 50 words). Then reply with one short sentence and stop."
  );
  out
}

/// The Verify instruction: re-check specific findings after a fix.
pub fn verify_prompt(findings: &[AdvisorFinding]) -> String {
  let mut out = format!(
    "You are the Advisor for a Rayfin app ({APP_SHAPE}). The findings below were reported earlier, and the developer has since changed the code to fix them. For each one, re-read the current code and decide whether the issue is still present.\n\n",
  );
  let _ = writeln!(out, "## Ground rules\n{GROUND_RULES}\n");
  let _ = writeln!(out, "## Findings to re-check");
  for (i, f) in findings.iter().enumerate() {
    let _ = writeln!(out, "\n{}. findingId `{}` — [{}] {}", i + 1, f.id, f.rule_id, f.title);
    if let Some(file) = &f.file {
      match f.line {
        Some(l) => {
          let _ = writeln!(out, "   Location: {file}:{l}");
        }
        None => {
          let _ = writeln!(out, "   Location: {file}");
        }
      }
    }
    let _ = writeln!(out, "   Problem: {}", f.detail);
    let _ = writeln!(out, "   Suggested fix: {}", f.recommendation);
    if let Some(excerpt) = f.excerpt.as_deref().filter(|e| !e.trim().is_empty()) {
      let _ = writeln!(out, "   Code when reported:\n```\n{excerpt}\n```");
    }
  }
  let _ = writeln!(
    out,
    "\n## How to report
Call `{VERDICT_TOOL}` once for EVERY finding above: `fixed` when the problem is gone (the code may have moved), `present` when it still occurs, or `unclear` when you can't tell. Add a one-sentence note. Then reply with one short sentence and stop."
  );
  out
}

/// The read-only "explain this finding" instruction (Markdown answer, no tools).
pub fn explain_prompt(finding: &AdvisorFinding) -> String {
  let location = match (finding.file.as_deref().map(str::trim).filter(|s| !s.is_empty()), finding.line) {
    (Some(f), Some(l)) => format!("{f}:{l}"),
    (Some(f), None) => f.to_string(),
    _ => "(not specific to one file)".to_string(),
  };
  let rule = super::catalog::rule(&finding.rule_id);
  let mut context = String::new();
  if let Some(rule) = rule {
    let _ = writeln!(context, "Rule: {} — {}", rule.id, rule.summary);
    let _ = writeln!(context, "Why the rule exists: {}", rule.why);
    let docs: Vec<String> = rule.docs.iter().map(|d| format!("{} ({})", d.title, d.url)).collect();
    let _ = writeln!(context, "Documentation: {}", docs.join("; "));
  }
  if let Some(url) = &finding.docs_url {
    let _ = writeln!(context, "Cited guidance: {url}");
  }
  let excerpt = finding
    .excerpt
    .as_deref()
    .filter(|e| !e.trim().is_empty())
    .map(|e| format!("\nCode:\n```\n{e}\n```\n"))
    .unwrap_or_default();
  format!(
    r#"You are helping the owner of a Rayfin app ({APP_SHAPE}). The Advisor flagged the issue below. Explain it in depth: what the underlying problem is, why it matters for THIS app (read the relevant code to ground your explanation), and how you would fix it.

This is a READ-ONLY explanation. Do not modify, create, or delete files, and do not run shell commands or deploys. Don't open `.env*` files or other secret stores. Only recommend APIs documented for the installed Rayfin version — the version-locked guide is in `node_modules/@microsoft/rayfin-guide/assets/docs/` and the live docs are at https://rayfin.ai.

Issue: {title}
Severity: {severity}
Category: {category}
Location: {location}
{context}
Details: {detail}
Suggested fix: {recommendation}
{excerpt}
Write a clear, friendly explanation in Markdown for a non-expert app owner: a few short paragraphs, with a short bullet list or a small fenced code snippet only where it genuinely helps. Be concrete to this codebase. Research silently — don't narrate what you're about to read or check. Don't restate this prompt and don't output JSON — reply with only the explanation."#,
    title = finding.title,
    severity = finding.severity,
    category = category_title(&finding.category),
    location = location,
    context = context,
    detail = finding.detail,
    recommendation = finding.recommendation,
    excerpt = excerpt,
  )
}

#[cfg(test)]
mod tests {
  use super::super::catalog::ai_rules_for;
  use super::*;
  use crate::types::{AdvisorFacts, AdvisorFactEntity, AdvisorQuickRef};

  fn request() -> AdvisorRunRequest {
    AdvisorRunRequest {
      model: None,
      effort: None,
      facts: AdvisorFacts {
        services: vec!["auth".into(), "data".into()],
        conditions: vec!["data".into(), "auth".into()],
        entities: vec![AdvisorFactEntity { name: "Todo".into(), file: "rayfin/data/Todo.ts".into(), access: "Row-scoped policy".into() }],
        versions: vec![],
        stack: Some("React + Vite".into()),
      },
      quick: vec![AdvisorQuickRef {
        rule_id: "data-model/text-without-max".into(),
        title: "Text field has no maximum length".into(),
        file: Some("rayfin/data/Todo.ts".into()),
        line: Some(7),
      }],
      previous: vec![],
    }
  }

  #[test]
  fn review_prompt_asks_to_recheck_the_last_reviews_findings() {
    let mut req = request();
    let rules = ai_rules_for(&req.facts.conditions);
    assert!(!review_prompt(&req, &rules).contains("re-check each one"));
    req.previous = vec![
      AdvisorQuickRef {
        rule_id: "queries/unpaginated-list".into(),
        title: "Todo list stops at 100 rows".into(),
        file: Some("src/todos.ts".into()),
        line: Some(12),
      },
      AdvisorQuickRef { rule_id: "not/a-listed-rule".into(), title: "Gone rule".into(), file: None, line: None },
    ];
    let prompt = review_prompt(&req, &rules);
    assert!(prompt.contains("re-check each one"));
    assert!(prompt.contains("[queries/unpaginated-list] Todo list stops at 100 rows — src/todos.ts:12"));
    assert!(!prompt.contains("Gone rule"), "rules outside this review can't be re-reported");
  }

  #[test]
  fn review_prompt_lists_every_applicable_rule_and_the_quick_findings() {
    let req = request();
    let rules = ai_rules_for(&req.facts.conditions);
    let prompt = review_prompt(&req, &rules);
    for rule in &rules {
      assert!(prompt.contains(&format!("`{}`", rule.id)), "missing {}", rule.id);
    }
    assert!(prompt.contains("[data-model/text-without-max] Text field has no maximum length — rayfin/data/Todo.ts:7"));
    assert!(prompt.contains("Todo (rayfin/data/Todo.ts) — Row-scoped policy"));
    assert!(prompt.contains(FINDING_TOOL) && prompt.contains(PROGRESS_TOOL) && prompt.contains(COMPLETE_TOOL));
    assert!(prompt.contains("READ-ONLY"));
    assert!(prompt.contains("rayfin-guide"));
  }

  #[test]
  fn verify_prompt_names_each_finding_id() {
    let finding = AdvisorFinding {
      id: "ai:queries/unpaginated-list:abc".into(),
      rule_id: "queries/unpaginated-list".into(),
      title: "List stops at 100 rows".into(),
      detail: "d".into(),
      recommendation: "r".into(),
      file: Some("src/a.ts".into()),
      line: Some(3),
      excerpt: Some("q.execute()".into()),
      ..Default::default()
    };
    let prompt = verify_prompt(&[finding]);
    assert!(prompt.contains("findingId `ai:queries/unpaginated-list:abc`"));
    assert!(prompt.contains("src/a.ts:3"));
    assert!(prompt.contains(VERDICT_TOOL));
  }
}
